### ISSUE TITLE
Answers on a postcard

### ISSUE THREAD

**Issue by sajattack** [thejpster/nrfxlib-sys#1]
I'm wondering if you could steal rust implementations of the C functions you need from [relibc](https://gitlab.redox-os.org/redox-os/relibc). It's not designed to target thumb, but might be portable?

**Comment by thejpster** [comment]
That's a good idea. I tried compiling in relibc whole, but it seems to need nightly. Sadly snprintf requires a C implementation as it's impossible to write var-args functions in Rust, but relibc has one of those as well.

I'll take a look.

**Comment by sajattack** [comment]
I'm pretty sure va-list was added recently.

**Comment by thejpster** [comment]
That's what relibc uses, but IIRC you still can't delare the variadic function itself in Rust.
